#!/bin/bash
#Build and run
echo "Building"

#if RaspiCam
g++ SmartCam.cpp ce_io.cpp `pkg-config --cflags --libs opencv` -std=c++11 -o SmartCam -I/usr/local/include/ -lraspicam -lraspicam_cv

#if USB webcam
#g++ SmartCam.cpp ce_io.cpp `pkg-config --cflags --libs opencv` -std=c++11 -o SmartCam

echo "Running"
gksudo ./SmartCam


